"""add mistake_count to weak_points

Revision ID: cfc7508f1beb
Revises: 
Create Date: 2025-01-29 07:47:20.051847

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cfc7508f1beb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('weak_points', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mistake_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('weak_points', schema=None) as batch_op:
        batch_op.drop_column('updated_at')
        batch_op.drop_column('mistake_count')

    # ### end Alembic commands ###
